/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContentFiltered = IDL.Record({
  'filteredText' : IDL.Text,
  'passed' : IDL.Bool,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isSupport' : IDL.Bool,
  'recipient' : IDL.Principal,
  'readByRecipient' : IDL.Bool,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const Conversation = IDL.Record({
  'participants' : IDL.Vec(IDL.Principal),
  'messages' : IDL.Vec(Message),
});
export const AreaMonitoring = IDL.Record({
  'accessLevel' : IDL.Nat,
  'description' : IDL.Text,
  'linkedCampaigns' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'regionName' : IDL.Text,
  'connectivityStatus' : IDL.Text,
  'coordinates' : Coordinates,
});
export const CommunityPost = IDL.Record({
  'id' : IDL.Nat,
  'moderationFlag' : IDL.Bool,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'anonymous' : IDL.Bool,
  'timestamp' : Time,
});
export const Institution = IDL.Record({
  'id' : IDL.Nat,
  'region' : IDL.Text,
  'infrastructureStatus' : IDL.Text,
  'contactInfo' : IDL.Text,
  'institutionType' : IDL.Text,
  'relatedCampaigns' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'awarenessRating' : IDL.Nat,
  'coordinates' : Coordinates,
});
export const OutreachCamp = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'endDate' : Time,
  'assignedClinician' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'coordinates' : Coordinates,
  'startDate' : Time,
  'eventType' : IDL.Text,
});
export const TherapySessionRequest = IDL.Record({
  'typeRequest' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const ReportedArea = IDL.Record({
  'description' : IDL.Text,
  'linkedCampaigns' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'hasMentalHealthSupport' : IDL.Bool,
  'regionName' : IDL.Text,
  'reporter' : IDL.Principal,
  'connectivityStatus' : IDL.Text,
  'coordinates' : Coordinates,
});
export const Language = IDL.Variant({
  'tamil' : IDL.Null,
  'hindi' : IDL.Null,
  'marathi' : IDL.Null,
  'spanish' : IDL.Null,
  'french' : IDL.Null,
  'kannada' : IDL.Null,
  'telugu' : IDL.Null,
  'english' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'languagePreference' : IDL.Opt(Language),
  'username' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CommunityGuidelines = IDL.Record({
  'acceptableConduct' : IDL.Vec(IDL.Text),
  'corePrinciples' : IDL.Text,
  'postingRules' : IDL.Vec(IDL.Text),
  'prohibitedBehaviors' : IDL.Vec(IDL.Text),
  'safetyGuidelines' : IDL.Vec(IDL.Text),
});
export const MoodEntry = IDL.Record({ 'mood' : IDL.Text, 'timestamp' : Time });
export const StressQuizResponse = IDL.Record({
  'responses' : IDL.Vec(IDL.Nat),
  'user' : IDL.Principal,
  'score' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAreaMonitoring' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), Coordinates],
      [],
      [],
    ),
  'addInstitution' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        Coordinates,
      ],
      [],
      [],
    ),
  'addMoodEntry' : IDL.Func([IDL.Text], [], []),
  'addOutreachCamp' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        IDL.Opt(IDL.Principal),
        IDL.Text,
        IDL.Text,
        Coordinates,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'canEditPost' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'checkAndAssignAdmin' : IDL.Func([], [IDL.Bool], []),
  'checkContent' : IDL.Func([IDL.Text], [ContentFiltered], ['query']),
  'createCommunityPost' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'createTherapySessionRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'editCommunityPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getActiveUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Time))],
      ['query'],
    ),
  'getAdminConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getAllAreaMonitoring' : IDL.Func([], [IDL.Vec(AreaMonitoring)], ['query']),
  'getAllCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'getAllCoordinates' : IDL.Func(
      [],
      [
        IDL.Record({
          'areas' : IDL.Vec(Coordinates),
          'camps' : IDL.Vec(Coordinates),
          'institutions' : IDL.Vec(Coordinates),
          'reportedAreas' : IDL.Vec(Coordinates),
        }),
      ],
      ['query'],
    ),
  'getAllInstitutions' : IDL.Func([], [IDL.Vec(Institution)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllOutreachCamps' : IDL.Func([], [IDL.Vec(OutreachCamp)], ['query']),
  'getAllTherapyRequests' : IDL.Func(
      [],
      [IDL.Vec(TherapySessionRequest)],
      ['query'],
    ),
  'getAppUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getAreaByRegion' : IDL.Func([IDL.Text], [IDL.Opt(ReportedArea)], ['query']),
  'getAreaMonitoringByRegion' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AreaMonitoring)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityGuidelines' : IDL.Func([], [CommunityGuidelines], ['query']),
  'getDashboardAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeCampaigns' : IDL.Nat,
          'distressedRegions' : IDL.Nat,
          'totalAreas' : IDL.Nat,
          'totalCamps' : IDL.Nat,
          'upcomingEvents' : IDL.Nat,
          'avgAwarenessRating' : IDL.Nat,
          'lowAccessAreas' : IDL.Nat,
          'totalInstitutions' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getInstitutionById' : IDL.Func([IDL.Nat], [IDL.Opt(Institution)], ['query']),
  'getMessagesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getOutreachCampById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(OutreachCamp)],
      ['query'],
    ),
  'getReportedAreas' : IDL.Func([], [IDL.Vec(ReportedArea)], ['query']),
  'getUniqueLoginsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserConversations' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getUserLanguagePreference' : IDL.Func([], [IDL.Opt(Language)], ['query']),
  'getUserMoodEntries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MoodEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserQuizResponse' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StressQuizResponse)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
  'moderatePost' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'recordSuccessfulLogin' : IDL.Func([], [], []),
  'reportArea' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, Coordinates],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Bool], [], []),
  'setAppUrl' : IDL.Func([IDL.Text], [], []),
  'setUserLanguagePreference' : IDL.Func([Language], [], []),
  'submitStressQuiz' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
  'updateAreaCampaigns' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'updateAreaMonitoring' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), Coordinates],
      [],
      [],
    ),
  'updateInstitution' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        Coordinates,
      ],
      [],
      [],
    ),
  'updateOutreachCamp' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        IDL.Opt(IDL.Principal),
        IDL.Text,
        IDL.Text,
        Coordinates,
      ],
      [],
      [],
    ),
  'updateUserActivity' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContentFiltered = IDL.Record({
    'filteredText' : IDL.Text,
    'passed' : IDL.Bool,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isSupport' : IDL.Bool,
    'recipient' : IDL.Principal,
    'readByRecipient' : IDL.Bool,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const Conversation = IDL.Record({
    'participants' : IDL.Vec(IDL.Principal),
    'messages' : IDL.Vec(Message),
  });
  const AreaMonitoring = IDL.Record({
    'accessLevel' : IDL.Nat,
    'description' : IDL.Text,
    'linkedCampaigns' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'regionName' : IDL.Text,
    'connectivityStatus' : IDL.Text,
    'coordinates' : Coordinates,
  });
  const CommunityPost = IDL.Record({
    'id' : IDL.Nat,
    'moderationFlag' : IDL.Bool,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'anonymous' : IDL.Bool,
    'timestamp' : Time,
  });
  const Institution = IDL.Record({
    'id' : IDL.Nat,
    'region' : IDL.Text,
    'infrastructureStatus' : IDL.Text,
    'contactInfo' : IDL.Text,
    'institutionType' : IDL.Text,
    'relatedCampaigns' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'awarenessRating' : IDL.Nat,
    'coordinates' : Coordinates,
  });
  const OutreachCamp = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'endDate' : Time,
    'assignedClinician' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'coordinates' : Coordinates,
    'startDate' : Time,
    'eventType' : IDL.Text,
  });
  const TherapySessionRequest = IDL.Record({
    'typeRequest' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const ReportedArea = IDL.Record({
    'description' : IDL.Text,
    'linkedCampaigns' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'hasMentalHealthSupport' : IDL.Bool,
    'regionName' : IDL.Text,
    'reporter' : IDL.Principal,
    'connectivityStatus' : IDL.Text,
    'coordinates' : Coordinates,
  });
  const Language = IDL.Variant({
    'tamil' : IDL.Null,
    'hindi' : IDL.Null,
    'marathi' : IDL.Null,
    'spanish' : IDL.Null,
    'french' : IDL.Null,
    'kannada' : IDL.Null,
    'telugu' : IDL.Null,
    'english' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'languagePreference' : IDL.Opt(Language),
    'username' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const CommunityGuidelines = IDL.Record({
    'acceptableConduct' : IDL.Vec(IDL.Text),
    'corePrinciples' : IDL.Text,
    'postingRules' : IDL.Vec(IDL.Text),
    'prohibitedBehaviors' : IDL.Vec(IDL.Text),
    'safetyGuidelines' : IDL.Vec(IDL.Text),
  });
  const MoodEntry = IDL.Record({ 'mood' : IDL.Text, 'timestamp' : Time });
  const StressQuizResponse = IDL.Record({
    'responses' : IDL.Vec(IDL.Nat),
    'user' : IDL.Principal,
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAreaMonitoring' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), Coordinates],
        [],
        [],
      ),
    'addInstitution' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          Coordinates,
        ],
        [],
        [],
      ),
    'addMoodEntry' : IDL.Func([IDL.Text], [], []),
    'addOutreachCamp' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          IDL.Opt(IDL.Principal),
          IDL.Text,
          IDL.Text,
          Coordinates,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'canEditPost' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'checkAndAssignAdmin' : IDL.Func([], [IDL.Bool], []),
    'checkContent' : IDL.Func([IDL.Text], [ContentFiltered], ['query']),
    'createCommunityPost' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'createTherapySessionRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'editCommunityPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getActiveUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Time))],
        ['query'],
      ),
    'getAdminConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getAllAreaMonitoring' : IDL.Func([], [IDL.Vec(AreaMonitoring)], ['query']),
    'getAllCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'getAllCoordinates' : IDL.Func(
        [],
        [
          IDL.Record({
            'areas' : IDL.Vec(Coordinates),
            'camps' : IDL.Vec(Coordinates),
            'institutions' : IDL.Vec(Coordinates),
            'reportedAreas' : IDL.Vec(Coordinates),
          }),
        ],
        ['query'],
      ),
    'getAllInstitutions' : IDL.Func([], [IDL.Vec(Institution)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllOutreachCamps' : IDL.Func([], [IDL.Vec(OutreachCamp)], ['query']),
    'getAllTherapyRequests' : IDL.Func(
        [],
        [IDL.Vec(TherapySessionRequest)],
        ['query'],
      ),
    'getAppUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getAreaByRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReportedArea)],
        ['query'],
      ),
    'getAreaMonitoringByRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AreaMonitoring)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityGuidelines' : IDL.Func([], [CommunityGuidelines], ['query']),
    'getDashboardAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeCampaigns' : IDL.Nat,
            'distressedRegions' : IDL.Nat,
            'totalAreas' : IDL.Nat,
            'totalCamps' : IDL.Nat,
            'upcomingEvents' : IDL.Nat,
            'avgAwarenessRating' : IDL.Nat,
            'lowAccessAreas' : IDL.Nat,
            'totalInstitutions' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getInstitutionById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Institution)],
        ['query'],
      ),
    'getMessagesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getOutreachCampById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(OutreachCamp)],
        ['query'],
      ),
    'getReportedAreas' : IDL.Func([], [IDL.Vec(ReportedArea)], ['query']),
    'getUniqueLoginsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserConversations' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getUserLanguagePreference' : IDL.Func([], [IDL.Opt(Language)], ['query']),
    'getUserMoodEntries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MoodEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserQuizResponse' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StressQuizResponse)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
    'moderatePost' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'recordSuccessfulLogin' : IDL.Func([], [], []),
    'reportArea' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          Coordinates,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Bool], [], []),
    'setAppUrl' : IDL.Func([IDL.Text], [], []),
    'setUserLanguagePreference' : IDL.Func([Language], [], []),
    'submitStressQuiz' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
    'updateAreaCampaigns' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'updateAreaMonitoring' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), Coordinates],
        [],
        [],
      ),
    'updateInstitution' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          Coordinates,
        ],
        [],
        [],
      ),
    'updateOutreachCamp' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          IDL.Opt(IDL.Principal),
          IDL.Text,
          IDL.Text,
          Coordinates,
        ],
        [],
        [],
      ),
    'updateUserActivity' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };