/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AreaMonitoring {
  'accessLevel' : bigint,
  'description' : string,
  'linkedCampaigns' : Array<string>,
  'timestamp' : Time,
  'regionName' : string,
  'connectivityStatus' : string,
  'coordinates' : Coordinates,
}
export interface CommunityGuidelines {
  'acceptableConduct' : Array<string>,
  'corePrinciples' : string,
  'postingRules' : Array<string>,
  'prohibitedBehaviors' : Array<string>,
  'safetyGuidelines' : Array<string>,
}
export interface CommunityPost {
  'id' : bigint,
  'moderationFlag' : boolean,
  'content' : string,
  'author' : Principal,
  'anonymous' : boolean,
  'timestamp' : Time,
}
export interface ContentFiltered { 'filteredText' : string, 'passed' : boolean }
export interface Conversation {
  'participants' : Array<Principal>,
  'messages' : Array<Message>,
}
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface Institution {
  'id' : bigint,
  'region' : string,
  'infrastructureStatus' : string,
  'contactInfo' : string,
  'institutionType' : string,
  'relatedCampaigns' : Array<string>,
  'name' : string,
  'awarenessRating' : bigint,
  'coordinates' : Coordinates,
}
export type Language = { 'tamil' : null } |
  { 'hindi' : null } |
  { 'marathi' : null } |
  { 'spanish' : null } |
  { 'french' : null } |
  { 'kannada' : null } |
  { 'telugu' : null } |
  { 'english' : null };
export interface Message {
  'id' : bigint,
  'content' : string,
  'isSupport' : boolean,
  'recipient' : Principal,
  'readByRecipient' : boolean,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface MoodEntry { 'mood' : string, 'timestamp' : Time }
export interface OutreachCamp {
  'id' : bigint,
  'status' : string,
  'endDate' : Time,
  'assignedClinician' : [] | [Principal],
  'name' : string,
  'description' : string,
  'location' : string,
  'coordinates' : Coordinates,
  'startDate' : Time,
  'eventType' : string,
}
export interface ReportedArea {
  'description' : string,
  'linkedCampaigns' : Array<string>,
  'timestamp' : Time,
  'hasMentalHealthSupport' : boolean,
  'regionName' : string,
  'reporter' : Principal,
  'connectivityStatus' : string,
  'coordinates' : Coordinates,
}
export interface StressQuizResponse {
  'responses' : Array<bigint>,
  'user' : Principal,
  'score' : bigint,
  'timestamp' : Time,
}
export interface TherapySessionRequest {
  'typeRequest' : string,
  'user' : Principal,
  'timestamp' : Time,
  'details' : string,
}
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'languagePreference' : [] | [Language],
  'username' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAreaMonitoring' : ActorMethod<
    [string, string, bigint, string, Array<string>, Coordinates],
    undefined
  >,
  'addInstitution' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      Array<string>,
      Coordinates,
    ],
    undefined
  >,
  'addMoodEntry' : ActorMethod<[string], undefined>,
  'addOutreachCamp' : ActorMethod<
    [
      string,
      string,
      string,
      Time,
      Time,
      [] | [Principal],
      string,
      string,
      Coordinates,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, string], undefined>,
  'canEditPost' : ActorMethod<[bigint], boolean>,
  'checkAndAssignAdmin' : ActorMethod<[], boolean>,
  'checkContent' : ActorMethod<[string], ContentFiltered>,
  'createCommunityPost' : ActorMethod<[string, boolean], undefined>,
  'createTherapySessionRequest' : ActorMethod<[string, string], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'editCommunityPost' : ActorMethod<[bigint, string], undefined>,
  'getActiveUsers' : ActorMethod<[], Array<[Principal, Time]>>,
  'getAdminConversations' : ActorMethod<[], Array<Conversation>>,
  'getAllAreaMonitoring' : ActorMethod<[], Array<AreaMonitoring>>,
  'getAllCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getAllCoordinates' : ActorMethod<
    [],
    {
      'areas' : Array<Coordinates>,
      'camps' : Array<Coordinates>,
      'institutions' : Array<Coordinates>,
      'reportedAreas' : Array<Coordinates>,
    }
  >,
  'getAllInstitutions' : ActorMethod<[], Array<Institution>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllOutreachCamps' : ActorMethod<[], Array<OutreachCamp>>,
  'getAllTherapyRequests' : ActorMethod<[], Array<TherapySessionRequest>>,
  'getAppUrl' : ActorMethod<[], string>,
  'getAreaByRegion' : ActorMethod<[string], [] | [ReportedArea]>,
  'getAreaMonitoringByRegion' : ActorMethod<[string], [] | [AreaMonitoring]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityGuidelines' : ActorMethod<[], CommunityGuidelines>,
  'getDashboardAnalytics' : ActorMethod<
    [],
    {
      'activeCampaigns' : bigint,
      'distressedRegions' : bigint,
      'totalAreas' : bigint,
      'totalCamps' : bigint,
      'upcomingEvents' : bigint,
      'avgAwarenessRating' : bigint,
      'lowAccessAreas' : bigint,
      'totalInstitutions' : bigint,
    }
  >,
  'getInstitutionById' : ActorMethod<[bigint], [] | [Institution]>,
  'getMessagesByUser' : ActorMethod<[Principal], Array<Message>>,
  'getOutreachCampById' : ActorMethod<[bigint], [] | [OutreachCamp]>,
  'getReportedAreas' : ActorMethod<[], Array<ReportedArea>>,
  'getUniqueLoginsCount' : ActorMethod<[], bigint>,
  'getUserConversations' : ActorMethod<[Principal], Array<bigint>>,
  'getUserLanguagePreference' : ActorMethod<[], [] | [Language]>,
  'getUserMoodEntries' : ActorMethod<[Principal], Array<MoodEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserQuizResponse' : ActorMethod<[Principal], [] | [StressQuizResponse]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[bigint], undefined>,
  'moderatePost' : ActorMethod<[bigint, boolean], undefined>,
  'recordSuccessfulLogin' : ActorMethod<[], undefined>,
  'reportArea' : ActorMethod<
    [string, string, string, Array<string>, boolean, Coordinates],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string, boolean], undefined>,
  'setAppUrl' : ActorMethod<[string], undefined>,
  'setUserLanguagePreference' : ActorMethod<[Language], undefined>,
  'submitStressQuiz' : ActorMethod<[bigint, Array<bigint>], undefined>,
  'updateAreaCampaigns' : ActorMethod<[string, Array<string>], undefined>,
  'updateAreaMonitoring' : ActorMethod<
    [string, string, bigint, string, Array<string>, Coordinates],
    undefined
  >,
  'updateInstitution' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      Array<string>,
      Coordinates,
    ],
    undefined
  >,
  'updateOutreachCamp' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Time,
      Time,
      [] | [Principal],
      string,
      string,
      Coordinates,
    ],
    undefined
  >,
  'updateUserActivity' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];