/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ReportedArea {
    description: string;
    linkedCampaigns: Array<string>;
    timestamp: Time;
    hasMentalHealthSupport: boolean;
    regionName: string;
    reporter: Principal;
    connectivityStatus: string;
    coordinates: Coordinates;
}
export type Time = bigint;
export interface Coordinates {
    latitude: number;
    longitude: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ContentFiltered {
    filteredText: string;
    passed: boolean;
}
export interface OutreachCamp {
    id: bigint;
    status: string;
    endDate: Time;
    assignedClinician?: Principal;
    name: string;
    description: string;
    location: string;
    coordinates: Coordinates;
    startDate: Time;
    eventType: string;
}
export interface MoodEntry {
    mood: string;
    timestamp: Time;
}
export interface CommunityPost {
    id: bigint;
    moderationFlag: boolean;
    content: string;
    author: Principal;
    anonymous: boolean;
    timestamp: Time;
}
export interface TherapySessionRequest {
    typeRequest: string;
    user: Principal;
    timestamp: Time;
    details: string;
}
export interface Message {
    id: bigint;
    content: string;
    isSupport: boolean;
    recipient: Principal;
    readByRecipient: boolean;
    sender: Principal;
    timestamp: Time;
}
export interface Institution {
    id: bigint;
    region: string;
    infrastructureStatus: string;
    contactInfo: string;
    institutionType: string;
    relatedCampaigns: Array<string>;
    name: string;
    awarenessRating: bigint;
    coordinates: Coordinates;
}
export interface CommunityGuidelines {
    acceptableConduct: Array<string>;
    corePrinciples: string;
    postingRules: Array<string>;
    prohibitedBehaviors: Array<string>;
    safetyGuidelines: Array<string>;
}
export interface StressQuizResponse {
    responses: Array<bigint>;
    user: Principal;
    score: bigint;
    timestamp: Time;
}
export interface AreaMonitoring {
    accessLevel: bigint;
    description: string;
    linkedCampaigns: Array<string>;
    timestamp: Time;
    regionName: string;
    connectivityStatus: string;
    coordinates: Coordinates;
}
export interface Conversation {
    participants: Array<Principal>;
    messages: Array<Message>;
}
export interface UserProfile {
    age: bigint;
    languagePreference?: Language;
    username: string;
    name: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Language {
    tamil = "tamil",
    hindi = "hindi",
    marathi = "marathi",
    spanish = "spanish",
    french = "french",
    kannada = "kannada",
    telugu = "telugu",
    english = "english"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAreaMonitoring(regionName: string, connectivityStatus: string, accessLevel: bigint, description: string, linkedCampaigns: Array<string>, coordinates: Coordinates): Promise<void>;
    addInstitution(name: string, institutionType: string, region: string, contactInfo: string, infrastructureStatus: string, awarenessRating: bigint, relatedCampaigns: Array<string>, coordinates: Coordinates): Promise<void>;
    addMoodEntry(mood: string): Promise<void>;
    addOutreachCamp(name: string, location: string, eventType: string, startDate: Time, endDate: Time, assignedClinician: Principal | null, status: string, description: string, coordinates: Coordinates): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserRole(user: Principal, role: string): Promise<void>;
    canEditPost(postId: bigint): Promise<boolean>;
    checkAndAssignAdmin(): Promise<boolean>;
    checkContent(text: string): Promise<ContentFiltered>;
    createCommunityPost(content: string, anonymous: boolean): Promise<void>;
    createTherapySessionRequest(typeRequest: string, details: string): Promise<void>;
    deletePost(postId: bigint): Promise<void>;
    editCommunityPost(postId: bigint, newContent: string): Promise<void>;
    getActiveUsers(): Promise<Array<[Principal, Time]>>;
    getAdminConversations(): Promise<Array<Conversation>>;
    getAllAreaMonitoring(): Promise<Array<AreaMonitoring>>;
    getAllCommunityPosts(): Promise<Array<CommunityPost>>;
    getAllCoordinates(): Promise<{
        areas: Array<Coordinates>;
        camps: Array<Coordinates>;
        institutions: Array<Coordinates>;
        reportedAreas: Array<Coordinates>;
    }>;
    getAllInstitutions(): Promise<Array<Institution>>;
    getAllMessages(): Promise<Array<Message>>;
    getAllOutreachCamps(): Promise<Array<OutreachCamp>>;
    getAllTherapyRequests(): Promise<Array<TherapySessionRequest>>;
    getAppUrl(): Promise<string>;
    getAreaByRegion(regionName: string): Promise<ReportedArea | null>;
    getAreaMonitoringByRegion(regionName: string): Promise<AreaMonitoring | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommunityGuidelines(): Promise<CommunityGuidelines>;
    getDashboardAnalytics(): Promise<{
        activeCampaigns: bigint;
        distressedRegions: bigint;
        totalAreas: bigint;
        totalCamps: bigint;
        upcomingEvents: bigint;
        avgAwarenessRating: bigint;
        lowAccessAreas: bigint;
        totalInstitutions: bigint;
    }>;
    getInstitutionById(id: bigint): Promise<Institution | null>;
    getMessagesByUser(user: Principal): Promise<Array<Message>>;
    getOutreachCampById(id: bigint): Promise<OutreachCamp | null>;
    getReportedAreas(): Promise<Array<ReportedArea>>;
    getUniqueLoginsCount(): Promise<bigint>;
    getUserConversations(user: Principal): Promise<Array<bigint>>;
    getUserLanguagePreference(): Promise<Language | null>;
    getUserMoodEntries(user: Principal): Promise<Array<MoodEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserQuizResponse(user: Principal): Promise<StressQuizResponse | null>;
    isCallerAdmin(): Promise<boolean>;
    markMessageAsRead(messageId: bigint): Promise<void>;
    moderatePost(postId: bigint, flag: boolean): Promise<void>;
    recordSuccessfulLogin(): Promise<void>;
    reportArea(regionName: string, connectivityStatus: string, description: string, linkedCampaigns: Array<string>, hasMentalHealthSupport: boolean, coordinates: Coordinates): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(recipient: Principal, content: string, isSupport: boolean): Promise<void>;
    setAppUrl(url: string): Promise<void>;
    setUserLanguagePreference(language: Language): Promise<void>;
    submitStressQuiz(score: bigint, responses: Array<bigint>): Promise<void>;
    updateAreaCampaigns(regionName: string, newCampaigns: Array<string>): Promise<void>;
    updateAreaMonitoring(regionName: string, connectivityStatus: string, accessLevel: bigint, description: string, linkedCampaigns: Array<string>, coordinates: Coordinates): Promise<void>;
    updateInstitution(id: bigint, name: string, institutionType: string, region: string, contactInfo: string, infrastructureStatus: string, awarenessRating: bigint, relatedCampaigns: Array<string>, coordinates: Coordinates): Promise<void>;
    updateOutreachCamp(id: bigint, name: string, location: string, eventType: string, startDate: Time, endDate: Time, assignedClinician: Principal | null, status: string, description: string, coordinates: Coordinates): Promise<void>;
    updateUserActivity(): Promise<void>;
}
import type { AreaMonitoring as _AreaMonitoring, Coordinates as _Coordinates, Institution as _Institution, Language as _Language, OutreachCamp as _OutreachCamp, ReportedArea as _ReportedArea, StressQuizResponse as _StressQuizResponse, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAreaMonitoring(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: Array<string>, arg5: Coordinates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAreaMonitoring(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAreaMonitoring(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addInstitution(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: Array<string>, arg7: Coordinates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInstitution(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInstitution(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addMoodEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMoodEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMoodEntry(arg0);
            return result;
        }
    }
    async addOutreachCamp(arg0: string, arg1: string, arg2: string, arg3: Time, arg4: Time, arg5: Principal | null, arg6: string, arg7: string, arg8: Coordinates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOutreachCamp(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOutreachCamp(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, arg1);
            return result;
        }
    }
    async canEditPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canEditPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canEditPost(arg0);
            return result;
        }
    }
    async checkAndAssignAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndAssignAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndAssignAdmin();
            return result;
        }
    }
    async checkContent(arg0: string): Promise<ContentFiltered> {
        if (this.processError) {
            try {
                const result = await this.actor.checkContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkContent(arg0);
            return result;
        }
    }
    async createCommunityPost(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCommunityPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCommunityPost(arg0, arg1);
            return result;
        }
    }
    async createTherapySessionRequest(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTherapySessionRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTherapySessionRequest(arg0, arg1);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async editCommunityPost(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCommunityPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCommunityPost(arg0, arg1);
            return result;
        }
    }
    async getActiveUsers(): Promise<Array<[Principal, Time]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveUsers();
            return result;
        }
    }
    async getAdminConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminConversations();
            return result;
        }
    }
    async getAllAreaMonitoring(): Promise<Array<AreaMonitoring>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAreaMonitoring();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAreaMonitoring();
            return result;
        }
    }
    async getAllCommunityPosts(): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCommunityPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCommunityPosts();
            return result;
        }
    }
    async getAllCoordinates(): Promise<{
        areas: Array<Coordinates>;
        camps: Array<Coordinates>;
        institutions: Array<Coordinates>;
        reportedAreas: Array<Coordinates>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoordinates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoordinates();
            return result;
        }
    }
    async getAllInstitutions(): Promise<Array<Institution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInstitutions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInstitutions();
            return result;
        }
    }
    async getAllMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessages();
            return result;
        }
    }
    async getAllOutreachCamps(): Promise<Array<OutreachCamp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOutreachCamps();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOutreachCamps();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTherapyRequests(): Promise<Array<TherapySessionRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTherapyRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTherapyRequests();
            return result;
        }
    }
    async getAppUrl(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppUrl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppUrl();
            return result;
        }
    }
    async getAreaByRegion(arg0: string): Promise<ReportedArea | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAreaByRegion(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAreaByRegion(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAreaMonitoringByRegion(arg0: string): Promise<AreaMonitoring | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAreaMonitoringByRegion(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAreaMonitoringByRegion(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunityGuidelines(): Promise<CommunityGuidelines> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityGuidelines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityGuidelines();
            return result;
        }
    }
    async getDashboardAnalytics(): Promise<{
        activeCampaigns: bigint;
        distressedRegions: bigint;
        totalAreas: bigint;
        totalCamps: bigint;
        upcomingEvents: bigint;
        avgAwarenessRating: bigint;
        lowAccessAreas: bigint;
        totalInstitutions: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardAnalytics();
            return result;
        }
    }
    async getInstitutionById(arg0: bigint): Promise<Institution | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstitutionById(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstitutionById(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesByUser(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesByUser(arg0);
            return result;
        }
    }
    async getOutreachCampById(arg0: bigint): Promise<OutreachCamp | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutreachCampById(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutreachCampById(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportedAreas(): Promise<Array<ReportedArea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportedAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportedAreas();
            return result;
        }
    }
    async getUniqueLoginsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniqueLoginsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniqueLoginsCount();
            return result;
        }
    }
    async getUserConversations(arg0: Principal): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserConversations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserConversations(arg0);
            return result;
        }
    }
    async getUserLanguagePreference(): Promise<Language | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLanguagePreference();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLanguagePreference();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMoodEntries(arg0: Principal): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMoodEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMoodEntries(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserQuizResponse(arg0: Principal): Promise<StressQuizResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserQuizResponse(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserQuizResponse(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markMessageAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageAsRead(arg0);
            return result;
        }
    }
    async moderatePost(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moderatePost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moderatePost(arg0, arg1);
            return result;
        }
    }
    async recordSuccessfulLogin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSuccessfulLogin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSuccessfulLogin();
            return result;
        }
    }
    async reportArea(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: boolean, arg5: Coordinates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportArea(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportArea(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async setAppUrl(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAppUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAppUrl(arg0);
            return result;
        }
    }
    async setUserLanguagePreference(arg0: Language): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserLanguagePreference(to_candid_Language_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserLanguagePreference(to_candid_Language_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitStressQuiz(arg0: bigint, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitStressQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitStressQuiz(arg0, arg1);
            return result;
        }
    }
    async updateAreaCampaigns(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAreaCampaigns(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAreaCampaigns(arg0, arg1);
            return result;
        }
    }
    async updateAreaMonitoring(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: Array<string>, arg5: Coordinates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAreaMonitoring(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAreaMonitoring(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateInstitution(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: Array<string>, arg8: Coordinates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInstitution(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInstitution(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateOutreachCamp(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: Time, arg6: Principal | null, arg7: string, arg8: string, arg9: Coordinates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOutreachCamp(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOutreachCamp(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
            return result;
        }
    }
    async updateUserActivity(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserActivity();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserActivity();
            return result;
        }
    }
}
function from_candid_Language_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_OutreachCamp_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OutreachCamp): OutreachCamp {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReportedArea]): ReportedArea | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AreaMonitoring]): AreaMonitoring | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Language]): Language | null {
    return value.length === 0 ? null : from_candid_Language_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Institution]): Institution | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OutreachCamp]): OutreachCamp | null {
    return value.length === 0 ? null : from_candid_OutreachCamp_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StressQuizResponse]): StressQuizResponse | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    endDate: _Time;
    assignedClinician: [] | [Principal];
    name: string;
    description: string;
    location: string;
    coordinates: _Coordinates;
    startDate: _Time;
    eventType: string;
}): {
    id: bigint;
    status: string;
    endDate: Time;
    assignedClinician?: Principal;
    name: string;
    description: string;
    location: string;
    coordinates: Coordinates;
    startDate: Time;
    eventType: string;
} {
    return {
        id: value.id,
        status: value.status,
        endDate: value.endDate,
        assignedClinician: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.assignedClinician)),
        name: value.name,
        description: value.description,
        location: value.location,
        coordinates: value.coordinates,
        startDate: value.startDate,
        eventType: value.eventType
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    languagePreference: [] | [_Language];
    username: string;
    name: string;
    email: string;
}): {
    age: bigint;
    languagePreference?: Language;
    username: string;
    name: string;
    email: string;
} {
    return {
        age: value.age,
        languagePreference: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.languagePreference)),
        username: value.username,
        name: value.name,
        email: value.email
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tamil: null;
} | {
    hindi: null;
} | {
    marathi: null;
} | {
    spanish: null;
} | {
    french: null;
} | {
    kannada: null;
} | {
    telugu: null;
} | {
    english: null;
}): Language {
    return "tamil" in value ? Language.tamil : "hindi" in value ? Language.hindi : "marathi" in value ? Language.marathi : "spanish" in value ? Language.spanish : "french" in value ? Language.french : "kannada" in value ? Language.kannada : "telugu" in value ? Language.telugu : "english" in value ? Language.english : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OutreachCamp>): Array<OutreachCamp> {
    return value.map((x)=>from_candid_OutreachCamp_n12(_uploadFile, _downloadFile, x));
}
function to_candid_Language_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    languagePreference?: Language;
    username: string;
    name: string;
    email: string;
}): {
    age: bigint;
    languagePreference: [] | [_Language];
    username: string;
    name: string;
    email: string;
} {
    return {
        age: value.age,
        languagePreference: value.languagePreference ? candid_some(to_candid_Language_n30(_uploadFile, _downloadFile, value.languagePreference)) : candid_none(),
        username: value.username,
        name: value.name,
        email: value.email
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    tamil: null;
} | {
    hindi: null;
} | {
    marathi: null;
} | {
    spanish: null;
} | {
    french: null;
} | {
    kannada: null;
} | {
    telugu: null;
} | {
    english: null;
} {
    return value == Language.tamil ? {
        tamil: null
    } : value == Language.hindi ? {
        hindi: null
    } : value == Language.marathi ? {
        marathi: null
    } : value == Language.spanish ? {
        spanish: null
    } : value == Language.french ? {
        french: null
    } : value == Language.kannada ? {
        kannada: null
    } : value == Language.telugu ? {
        telugu: null
    } : value == Language.english ? {
        english: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
